version: 2
jobs:
  build:
    docker:
      - image:  conanio/gcc9
    steps:
      - checkout
      - run:
          name: Creating Build Files
          command: 'mkdir build && cd build && cmake ..'

workflows:
  version: 2
  build:
    jobs:
      - build
